apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: stateful-operator
  name: stateful-operator
  namespace: bullyun-third
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stateful-operator
  template:
    metadata:
      labels:
        app: stateful-operator
    spec:
      terminationGracePeriodSeconds: 70
      serviceAccountName: stateful-operator
      imagePullSecrets:
        - name: registry-secret
      containers:
        - name: stateful-operator
          image: registry.cn-hangzhou.aliyuncs.com/bullyun/stateful-operator:1.0
          imagePullPolicy: Always
          securityContext:
            privileged: true
          command:
            - stateful-operator
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "stateful-operator"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: bullyun.storage.node
                    values:
                      - "true"
                    operator: In
