
apiVersion: v1
kind: ServiceAccount
metadata:
  name: stateful-operator
  namespace: bullyun-third
---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: stateful-operator
  namespace: bullyun-third
subjects:
  - kind: ServiceAccount
    name: stateful-operator
roleRef:
  kind: Role
  name: stateful-operator
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: stateful-operator
  namespace: bullyun-third
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - "*"
